import pytest
import pandas as pd
import numpy as np

# Mock function to simulate the preprocessing pipeline for XGBoost
# In a real scenario, this would be imported from ml.recomendacion or ml.features
def preprocess_financial_data(data: pd.DataFrame) -> pd.DataFrame:
    """
    Simulates the addition of technical indicators used by the XGBoost model.
    Expected output should have specific columns like 'SMA_20', 'RSI_14', etc.
    """
    df = data.copy()
    if df.empty:
        return df

    # Example: Simple Moving Average
    df['SMA_20'] = df['Close'].rolling(window=20).mean()
    # Example: Daily Return
    df['Daily_Return'] = df['Close'].pct_change()
    
    # Drop NaNs that are generated by rolling windows
    df = df.dropna()
    return df

@pytest.fixture
def mock_stock_data():
    """Generates 30 days of mock stock OHLCV data."""
    dates = pd.date_range(start='2023-01-01', periods=30)
    data = {
        'Open': np.random.uniform(100, 150, 30),
        'High': np.random.uniform(150, 160, 30),
        'Low': np.random.uniform(90, 100, 30),
        'Close': np.random.uniform(105, 145, 30),
        'Volume': np.random.randint(1000, 10000, 30)
    }
    return pd.DataFrame(data, index=dates)

def test_preprocessing_adds_expected_features(mock_stock_data):
    """Verifies that the preprocessing function adds necessary technical indicators."""
    processed_df = preprocess_financial_data(mock_stock_data)
    
    # We expect these columns to be present for the ML model
    expected_columns = ['SMA_20', 'Daily_Return']
    for col in expected_columns:
        assert col in processed_df.columns, f"Feature {col} is missing from preprocessed data"

def test_preprocessing_handles_nans(mock_stock_data):
    """Verifies that the preprocessing function correctly drops or fills NaNs."""
    processed_df = preprocess_financial_data(mock_stock_data)
    
    assert not processed_df.isnull().values.any(), "Preprocessed data contains NaN values"

def test_preprocessing_dimensions():
    """Verifies the shape of the output dataframe."""
    dates = pd.date_range(start='2023-01-01', periods=25)
    data = {'Close': np.linspace(100, 124, 25)}
    df = pd.DataFrame(data, index=dates)
    
    processed_df = preprocess_financial_data(df)
    
    # Since we have a rolling window of 20, we expect 25 - 19 = 6 rows left
    assert len(processed_df) == 6, f"Expected 6 rows after preprocessing, got {len(processed_df)}"
